##############################################################
#### ANET Server Configuration 
####
#### This is the configuration file for the ANET server. 
####
#### For Production use, replace all areas with ${NAME} with 
#### the correct values for your installation.
####
#### For Development use, create a file called `localSettings.gradle`
#### And set each environment variable there 
####  ie: `run.environment('ANET_SMTP_SERVER', 'my-mail-server.example.com`)
#### Do not make any changes to this file unless they apply to all 
#### developers! 
#### 
##############################################################

# Flag to run the server in development mode
# - Will use Basic authentication (rather than Windows Domain Auth)
# - Will reload the GraphQL Graph on every request. 
developmentMode: true

# Settings for the SMTP server to send email 
smtp:
  hostname: ${ANET_SMTP_SERVER}
  port: 25
  username: ${ANET_SMTP_USERNAME}
  password: ${ANET_SMTP_PASSWORD}
  startTls: true

# The email address that all automated emails should come from. 
# ex: "ANET <anet@example.com>"
emailFromAddr: "Anet Testing <hunter+anet@dds.mil>"

# The URL that should be used for links in emails
# ex:  "http://anet.yourdomain"
# Should not include an ending slash! 
serverUrl: "http://localhost:3000"

# Configuration for Waffle. This is the system that ANET uses to perform windows authentication
# See https://github.com/Waffle/waffle
waffleConfig:
  principalFormat: fqn
  roleFormat: both
  allowGuestLogin: false
  impersonate: false
  securityFilterProviders: waffle.servlet.spi.BasicSecurityFilterProvider
  #securityFilterProviders: "waffle.servlet.spi.BasicSecurityFilterProvider waffle.servlet.spi.NegotiateSecurityFilterProvider"
  #"waffle.servlet.spi.NegotiateSecurityFilterProvider/protocols": Negotiate NTLM
  "waffle.servlet.spi.BasicSecurityFilterProvider/realm": ANET

########################################################
### The below is the default Dropwizard Configuration
### See http://www.dropwizard.io/1.0.6/docs/manual/configuration.html#man-configuration
### For all of the possible configuration options. 
#########################################################
# Configuration for the database Server
# See http://www.dropwizard.io/1.0.6/docs/manual/jdbi.html#configuration
database:
  driverClass: ${ANET_DB_DRIVER}
  user: ${ANET_DB_USERNAME}
  password: ${ANET_DB_PASSWORD}
  url: ${ANET_DB_URL}
  properties:
   date_string_format: ${ANET_DB_DATE_STRING_FORMAT}
   date_class: ${ANET_DB_DATE_CLASS}


# Configuration for the web servers HTTP connectors. 
# See http://www.dropwizard.io/1.0.6/docs/manual/core.html#configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
# The AdminConnector is used for administrative functions of Dropwizard and should not be exposed to users. 
  adminConnectors:
    - type: http
      port: 8081

# Configuration for the Freemarker templating library
views:
  .ftl:
    number_format: computer

logging:
  level: INFO
  loggers:
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper" : TRACE
    "org.skife.jdbi.v2.DBI" :
      level: TRACE
      appenders:
        - type: file
#          additive: false
          currentLogFilename: ./logs/dbLog.log
          archivedLogFilenamePattern: ./logs/dbLog-%d.log.zip
          archivedFileCount: 2
    "org.sqlite.JDBC" : INFO
    "io.dropwizard.assets.AssetsBundle" : TRACE
    "io.dropwizard.assets.*" : TRACE
    "waffle.servlet.NegotiateSecurityFilter" : TRACE
    "mil.dds.anet.auth.AnetAuthenticationFilter" : TRACE
    "mil.dds.anet.AnetEmailWorker" : DEBUG
    "mil.dds.anet.resources.TestingResource" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/testingLogger.log
          archivedLogFilenamePattern: ./logs/testingLogger-%d.log.zip
          archivedFileCount: 2
    "mil.dds.anet.utils.AnetAuditLogger" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/auditLogger.log
          archivedLogFilenamePattern: ./logs/auditLogger-%d.log.zip
          archivedFileCount: 2
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
