##############################################################
#### ANET Server Configuration 
####
#### This is the configuration file for the ANET server. 
####
#### For Production use, replace all areas with ${NAME} with 
#### the correct values for your installation.
####
#### For Development use, create a file called `localSettings.gradle`
#### And set each environment variable there 
####  ie: `run.environment('ANET_SMTP_SERVER', 'my-mail-server.example.com`)
#### Do not make any changes to this file unless they apply to all 
#### developers! 
#### 
##############################################################

# Flag to run the server in development mode
# - Will use Basic authentication (rather than Windows Domain Auth)
# - Will reload the GraphQL Graph on every request. 
developmentMode: true

# Flag to tell the server to redirect all HTTP traffic to HTTPS
# You will need to add an HTTP/80 adapter
redirectToHttps: false

# Settings for the SMTP server to send email 
smtp:
  hostname: ${ANET_SMTP_SERVER}
  port: 25
  username: ${ANET_SMTP_USERNAME}
  password: ${ANET_SMTP_PASSWORD}
  startTls: true
  disabled: true

# The email address that all automated emails should come from. 
# ex: "ANET <anet@example.com>"
emailFromAddr: "Anet Testing <hunter+anet@dds.mil>"

# The URL that should be used for links in emails
# ex:  "http://anet.yourdomain"
# Should not include an ending slash! 
serverUrl: "http://localhost:3000"

# Configuration for Waffle. This is the system that ANET uses to perform windows authentication
# See https://github.com/Waffle/waffle
waffleConfig:
  principalFormat: fqn
  roleFormat: both
  allowGuestLogin: false
  impersonate: false
  securityFilterProviders: waffle.servlet.spi.BasicSecurityFilterProvider
  #securityFilterProviders: "waffle.servlet.spi.BasicSecurityFilterProvider waffle.servlet.spi.NegotiateSecurityFilterProvider"
  #"waffle.servlet.spi.NegotiateSecurityFilterProvider/protocols": NTLM
  "waffle.servlet.spi.BasicSecurityFilterProvider/realm": ANET

########################################################
### The below is the default Dropwizard Configuration
### See http://www.dropwizard.io/1.0.6/docs/manual/configuration.html#man-configuration
### For all of the possible configuration options. 
#########################################################
# Configuration for the database Server
# See http://www.dropwizard.io/1.0.6/docs/manual/jdbi.html#configuration
database:
  driverClass: ${ANET_DB_DRIVER}
  user: ${ANET_DB_USERNAME}
  password: ${ANET_DB_PASSWORD}
  url: ${ANET_DB_URL}
  properties:
   date_string_format: ${ANET_DB_DATE_STRING_FORMAT}
   date_class: ${ANET_DB_DATE_CLASS}


# Configuration for the web servers HTTP connectors. 
# See http://www.dropwizard.io/1.0.6/docs/manual/core.html#configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
# The AdminConnector is used for administrative functions of Dropwizard and should not be exposed to users. 
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: 
      - type: file
        currentLogFilename: ./logs/access.log
        archivedLogFilenamePattern: ./logs/access-%d.log.zip
        archivedFileCount: 5
      - type: console
        target: stdout

# Configuration for the Freemarker templating library
views:
  .ftl:
    number_format: computer

logging:
  level: INFO
  loggers:
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper" : TRACE
    "org.skife.jdbi.v2.DBI" :
      level: TRACE
      appenders:
        - type: file
#          additive: false
          currentLogFilename: ./logs/dbLog.log
          archivedLogFilenamePattern: ./logs/dbLog-%d.log.zip
          archivedFileCount: 2
    "org.sqlite.JDBC" : INFO
    "io.dropwizard.assets.AssetsBundle" : TRACE
    "io.dropwizard.assets.*" : TRACE
    "waffle.servlet.NegotiateSecurityFilter" : TRACE
    "mil.dds.anet.auth.AnetAuthenticationFilter" : TRACE
    "mil.dds.anet.threads.AnetEmailWorker" : DEBUG
    "mil.dds.anet.threads.FutureEngagementWorker" : DEBUG
    "mil.dds.anet.resources.TestingResource" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/testingLogger.log
          archivedLogFilenamePattern: ./logs/testingLogger-%d.log.zip
          archivedFileCount: 2
    "mil.dds.anet.utils.AnetAuditLogger" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/auditLogger.log
          archivedLogFilenamePattern: ./logs/auditLogger-%d.log.zip
          archivedFileCount: 2
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/anet.log
      archivedLogFilenamePattern: ./logs/anet-%d.log.zip
      archivedFileCount: 2

dictionary:
  PRINCIPAL_PERSON_TITLE: Afghan Partner
  ADVISOR_PERSON_TITLE: NATO Member
  PRINCIPAL_POSITION_NAME: Afghan Tashkil
  ADVISOR_POSITION_NAME: NATO Billet
  ADVISOR_POSITION_TYPE_TITLE: NATO Advisor
  SUPER_USER_POSITION_TYPE_TITLE: ANET Super User
  ADMINISTRATOR_POSITION_TYPE_TITLE: ANET Administrator
  PRINCIPAL_ORG_NAME: Afghan Government Organization
  ADVISOR_ORG_NAME: Advisor Organization
  POAM_LONG_NAME: Plan of Action and Milestones / Pillars
  POAM_SHORT_NAME: PoAM
  NAV_BAR_ALL_ADVISOR_ORGS: All EFs / AOs
  pinned_ORGs:
    - Key Leader Engagement
  countries:
    - Afghanistan
    - Albania
    - Armenia
    - Australia
    - Austria
    - Azerbaijan
    - Belgium
    - Bosnia-Herzegovina
    - Bulgaria
    - Croatia
    - Czech Republic
    - Denmark
    - Estonia
    - Finland
    - Georgia
    - Germany
    - Greece
    - Hungary
    - Iceland
    - Italy
    - Latvia
    - Lithuania
    - Luxembourg
    - Macedonia
    - Mongolia
    - Montenegro
    - Netherlands
    - New Zealand
    - Norway
    - Poland
    - Portugal
    - Romania
    - Slovakia
    - Slovenia
    - Spain
    - Sweden
    - Turkey
    - Ukraine
    - United Kingdom
    - United States of America
  ranks:
    - CIV
    - CTR
    - OR-1
    - OR-2
    - OR-3
    - OR-4
    - OR-5
    - OR-6
    - OR-7
    - OR-8
    - OR-9
    - WO-1
    - WO-2
    - WO-3
    - WO-4
    - WO-5
    - OF-1
    - OF-2
    - OF-3
    - OF-4
    - OF-5
    - OF-6
    - OF-7
    - OF-8
    - OF-9
    - OF-10
