person(f:me) {
    id, name, role
    position {
        id, name, type,
        organization { id, shortName, longName }
    }
}

adminSettings(f:getAll) {
    key, value
}
organizations(f:getTopLevelOrgs, type: ADVISOR_ORG) {
    id, shortName, longName
    parentOrg { id }
}
