person(f:me) {
    id, name, role
    position {
        id, name, type,
        organization { id, shortName, longName }
    }
}

adminSettings(f:getAll) {
    key, value
}
organizationList(f:getTopLevelOrgs, type: ADVISOR_ORG) {
	list { 
	    id, shortName, longName
	    parentOrg { id }
	}
}
