organization(id:${orgId}) {
    id, name, type
    parentOrg { id, name }
    poams { id, longName, shortName }
    positions {
        id, name, code
        person { id, name }
        associatedPositions {
            id, name, code
            person { id, name }
        }
    },
    childrenOrgs { id, name },
    approvalSteps {
        approverGroup {
            id, name, members { id, name , position { id, name} }
        }
    }
}
