person(id:${personId}) {
    id,
    name, rank, role, emailAddress, phoneNumber, biography, country, gender, endOfTourDate
    position {
        id,
        name,
        organization {
            id,
            shortName, longName
        }
    },
    authoredReports(pageNum:0,pageSize:10) { list { 
        id,
        engagementDate,
        advisorOrg { id, shortName, longName }
        intent,
        author {
            id,
            name
        }
    }},
    attendedReports(pageNum:0, pageSize:10) { list { 
        id,
        engagementDate,
        advisorOrg { id, shortName, longName}
        intent,
        author {
            id,
            name
        }
    }}

}
