position(id:${positionId}) {
    id, name, type, code,
    organization { id, shortName, longName },
    person { id, name, rank },
    associatedPositions {
        id, name,
        person { id, name }
    },
    location { id, name }
}
