report(id:${reportId}) {
    id, intent, engagementDate, atmosphere, atmosphereDetails
    keyOutcomes, nextSteps, reportText, 

    state

    location { id, name }
    author {
        id, name
        position {
            organization {
                shortName, longName
                approvalSteps {
                    id, name,
                    approvers {
                        id, name,
                        person { id, name rank }
                    }
                }
            }
        }
    }

    attendees {
        id, name, role, primary
        position { id, name }
    }
    primaryAdvisor { id }
    primaryPrincipal { id }

    poams { id, shortName, longName, responsibleOrg { id, shortName} }

    comments {
        id, text, createdAt, updatedAt
        author { id, name, rank }
    }

    principalOrg { id, shortName, longName }
    advisorOrg { id, shortName, longName }

    approvalStatus {
        type, createdAt
        step { id , name
            approvers { id, name, person { id, name } }
        },
        person { id, name, rank}
    }

    approvalStep { name, approvers { id } }

}
