searchResults(f:search, q:"${searchQuery}") {
	reports { list { id, intent, engagementDate, keyOutcomes, nextSteps
        primaryAdvisor { id, name, position { organization { id, shortName, longName}}},
        primaryPrincipal { id, name, position { organization { id, shortName, longName}}},
        advisorOrg { id, shortName, longName},
        principalOrg { id, shortName, longName},
        location { id, name},
        poams {id, shortName, longName}
	}},
    people { totalCount, list { id, name, rank, emailAddress }}
    positions { totalCount, list { id, name, type, organization{ id, shortName} , person { id, name}}}
    poams { totalCount, list { id, shortName, longName}}
    locations { totalCount, list { id, name, lat, lng}}
    organizations { totalCount, list { id, shortName, longName }}
}
