reportList (f:search, query:{text:"${searchQuery}"}) {
	list { id, intent, engagementDate, keyOutcomes, nextSteps
        primaryAdvisor { id, name, position { organization { id, shortName, longName}}},
        primaryPrincipal { id, name, position { organization { id, shortName, longName}}},
        advisorOrg { id, shortName, longName},
        principalOrg { id, shortName, longName},
        location { id, name},
        poams {id, shortName, longName}
	}
}

personList(f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { id, name, rank, emailAddress }
}
positionList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { id, name, type, organization{ id, shortName} , person { id, name}}
}
poamList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { id, shortName, longName}
}
locationList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { id, name, lat, lng}
}
organizationList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { id, shortName, longName }
}

